#cloud-config
hostname: proxy
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmjoVIoZCx4QFXvljqozXGqxxlSvO7V2aizqyPgMfGqnyl0J9YXo6zrcWYwyWMnMdRdwYZgHqfiiFCUn2QDm6ZuzC4Lcx0K3ZwO2lgL4XaATykVLneHR1ib6RNroFcClN69cxWsdwQW6dpjpiBDXf8m6/qxVP3EHwUTsP8XaOV7WkcCAqfYAMvpWLISqYme6e+6ZGJUIPkDTxavu5JTagDLwY+py1WB53eoDWsG99gmvyit2O1Eo+jRWN+mgRHIxJTrFtLS6o4iWeshPZ6LvCZ/Pum12Oj4B4bjGSHzrKjHZgTwhVJ/LDq3v71/PP4zaI3gVB9ZalemSxqomgbTlnT jose@debian
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text

runcmd:
  - apt update
  - apt install -y apache2 iptables
  - sysctl -w net.ipv4.ip_forward=1
  - iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -j MASQUERADE
  - systemctl enable apache2
  - systemctl start apache2

write_files:
  - path: /etc/hosts
    append: true
    content: |
      10.0.0.2 interno.example.org
